apiVersion: gitlab.ogen.krateo.io/v1alpha1
kind: RepoConfiguration
metadata:
  name: my-gitlab-repo-config
  namespace: default
spec:
  authentication:
    bearer:
      # Reference to a secret containing the bearer token
      tokenRef:
        name: gitlab-token        # Name of the secret
        namespace: default        # Namespace where the secret exists
        key: token                # Key within the secret that contains the token
  configuration:
    query:
      findby:
        membership: true          # Limit by projects that the current user is a member of.
        simple: true              # Limits the response body of the findby action to the most important fields.
